### ISSUE TITLE
Implement the first batch of Serialization / IO / Conversion functions

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#169]
See https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#serialization-io-conversion

Looks like we can easily implement almost all of them by calling `toPandas().func_name()`.

One thing is that some of the functions support `max_rows`. When that argument is specified, we should add a `limit` call in Spark to avoid moving all the data to the driver.

The list to add in the first batch are:

- [x] to_dict (see #169)
- [x] to_excel (#288)
- [x] to_html (we already have this, but let's add a limit when max_rows is set), done in #206
- [x] to_latex (#297)
- [x] to_records (#298)
- [x] to_string (done in #211 and #213)
- [x] to_clipboard (#257)

Skipping the following because I don't know how popular they are:

- to_pickle
- to_hdf
- to_stata
- to_msgpack
- to_records
- to_sparse
- to_dense

The following might require parallelization with Pandas UDFs, rather than collecting all the data to the driver, so leaving them for the future:

- to_sql
- to_gbq

I'm also not adding json and csv here. We need to design those properly because both Spark and Pandas have those.

**Comment by rxin** [comment]
For contributors -- in general this is a pretty easy one to get started. Just look at how we did https://github.com/databricks/koalas/pull/211 and https://github.com/databricks/koalas/pull/213

**Comment by arjun180** [comment]
Can I work on this?

**Comment by HyukjinKwon** [comment]
please go ahead.

**Comment by shril** [comment]
@rxin , @HyukjinKwon Can I take this up as well?

**Comment by rxin** [comment]
Go for it.

**Comment by HyukjinKwon** [comment]
I think we should do `to_json` too.

**Comment by garawalid** [comment]
@rxin 
> I'm also not adding json and csv here. We need to design those properly because both Spark and Pandas have those.

I agree with @HyukjinKwon, we can add `to_json` & `to_csv`. 
In fact, both methods need to collect data in the driver through `toPandas()`. And if we pass the path as a parameter, the output will be saved in the driver. This is what Pandas users will expect, at least, those who are not familiar with Spark. 

In the case of Spark, I think we should keep `to_csv` and `to_json` in a separate section than `Serialization / IO / Conversion` and we explain the behaviour in the documentation. These methods will be useful if we want to write the output in HDFS without impacting the performance.

Btw, `to_clipboard` uses `to_csv`.

**Comment by HyukjinKwon** [comment]
We can support both hdfs and local path and that's what Spark currently supports. Let's keep it consistent first before we start to have some divergence.

We can explain the difference in the docstring with notes and I think that's already what are doing.

**Comment by rxin** [comment]
@garawalid do you want to do the rest as well?

**Comment by garawalid** [comment]
@rxin 
Of course, I'll handle the rest! 
You can close it.

**Comment by rxin** [comment]
We only close the ticket once all the items are done :)

**Comment by shril** [comment]
@garawalid are you doing to_excel function?

**Comment by garawalid** [comment]
@shril not yet! You can pick it up.

**Comment by abishekganesh72** [comment]
I can take up one of the functions. Let me know if something is available.

**Comment by HyukjinKwon** [comment]
Please say that you're working on some functions here and go ahead.

**Comment by athena15** [comment]
Working on .to_latex() function. Pull request coming soon.

**Comment by abishekganesh72** [comment]
Working on to_records

**Comment by rxin** [comment]
Thank you all!

**Comment by shril** [comment]
@rxin, I have implemented `to_records` in  PR #298.
Can you please close this issue?

**Comment by HyukjinKwon** [comment]
Thanks, @shril. This issue is nicely finished.
