### ISSUE TITLE
Implement plots and switch the default plot backend to plotly

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#1933]
I took a look for the plots not implemented for Plotly, which we can actually implement:

- [x] `DataFrame.plot.area` (https://plotly.com/python/filled-area-plots/): https://github.com/databricks/koalas/pull/1934
  
- [x] `DataFrame.plot.hist` (https://plotly.com/python/histograms/) #1999 

    ![Screen Shot 2021-01-12 at 10 12 47 PM](https://user-images.githubusercontent.com/6477701/104318885-644e4700-5523-11eb-81bc-f56ea1dbe797.png)

- [x] ~~`DataFrame.plot.box` (https://plotly.com/python/box-plots/)~~ this is not implemented yet in Koalas
- [x] `DataFrame.plot.kde` (https://plotly.com/python/line-charts/) #2028

    ![fig1](https://user-images.githubusercontent.com/6477701/106457713-b6570c80-64d2-11eb-9eaf-afffa16a923a.png)

- [x] `DataFrame.plot.pie` (https://plotly.com/python/pie-charts/): https://github.com/databricks/koalas/pull/1971

    ![Screen Shot 2020-12-17 at 3 28 12 PM](https://user-images.githubusercontent.com/6477701/102451779-87005380-407c-11eb-85f3-aa2d8e62c991.png)

- [x] `Series.plot.box` (https://plotly.com/python/box-plots/) #2007 

    ![Screen Shot 2021-01-14 at 6 56 19 PM](https://user-images.githubusercontent.com/6477701/104575700-acdc4080-569a-11eb-8d55-0ac3db800ddd.png)

- [x] `Series.plot.hist` (https://plotly.com/python/histograms/) #1999

- [x] `Series.plot.pie` (https://plotly.com/python/pie-charts/): https://github.com/databricks/koalas/pull/1971
- [x] `Series.plot.kde` (https://plotly.com/python/line-charts/) #2028
- [x] Switch plotting backend to plotly by default. #2033

**Comment by itholic** [comment]
Seems like now we can close this issue ?

**Comment by HyukjinKwon** [comment]
There's one last left #2033
