### ISSUE TITLE
Convert global or limit-related variables into configurations.

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#715]
https://github.com/databricks/koalas/commit/94adf06d622aaac1eb05c03407db8a1abc01632c added configuration base like Pandas. See https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

Currently we have multiple variables that should be converted into configuration values. We should identify and convert it to configuration _all_.

- [x] Support typed values in configurations (#714)
- [x] Add 'display.max_rows' (#714)
- [x] Add 'compute.shortcut_limit' (#717) https://github.com/databricks/koalas/blob/8360c586f5ad4c8847fe394eefbd77b48d95f687/databricks/koalas/frame.py#L373-L379
- [x] Add 'compute.max_rows'  (#721) https://github.com/databricks/koalas/blob/8360c586f5ad4c8847fe394eefbd77b48d95f687/databricks/koalas/frame.py#L1463-L1470 (I think we should remove `limit` parameter).
- [x] Add 'compute.shortcut_limit' (#717) https://github.com/databricks/koalas/blob/8360c586f5ad4c8847fe394eefbd77b48d95f687/databricks/koalas/groupby.py#L806-L812
- [x] Add 'compute.shortcut_limit' (#717) https://github.com/databricks/koalas/blob/8360c586f5ad4c8847fe394eefbd77b48d95f687/databricks/koalas/groupby.py#L1512-L1518
- [x] Add 'plotting.max_rows'  (#728) https://github.com/databricks/koalas/blob/8360c586f5ad4c8847fe394eefbd77b48d95f687/databricks/koalas/plot.py#L54
- [x] Add 'plotting.sample_ratio' (#737) https://github.com/databricks/koalas/blob/8360c586f5ad4c8847fe394eefbd77b48d95f687/databricks/koalas/plot.py#L85
- [x] Add 'compute.ops_on_diff_frames' (#725) https://github.com/databricks/koalas/blob/8360c586f5ad4c8847fe394eefbd77b48d95f687/databricks/koalas/utils.py#L63
- [x] Add 'compute.default_index_type' (#723) https://github.com/databricks/koalas/blob/8360c586f5ad4c8847fe394eefbd77b48d95f687/databricks/koalas/internal.py#L477
- [x] Add 'compute.max_rows' (#736) https://github.com/databricks/koalas/pull/712/files#diff-5ba644c40e914732959b9b4867f30c53R1644
- [x] Add 'compute.shortcut_limit' (#739) https://github.com/databricks/koalas/pull/732/files#diff-5ba644c40e914732959b9b4867f30c53R1605
- [ ] Add documentation (#743). See https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

**Comment by HyukjinKwon** [comment]
@itholic are you interested in working of some of them? Don't have to do everything in one go.

**Comment by HyukjinKwon** [comment]
cc @RainFung and @charlesdong1991 too just in case you guys are interested in this.

**Comment by charlesdong1991** [comment]
nice one! what a coincidence! i asked if `max_rows` should be flexible or not yesterday, and today issue is here 😆  i am working on `scatter` and `hexbin` plots now, but would like to take `Add 'plotting.max_rows'` and `Add 'plotting.sample_ratio'` later if you don't mind. @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Please go ahead for both items!

**Comment by ueshin** [comment]
@HyukjinKwon As for `SPARK_KOALAS_AUTOPATCH` and `KOALAS_USAGE_LOGGER`, we need them when initializing Koalas, so we shouldn't use the configurations.
I removed them from the list in the description.

**Comment by HyukjinKwon** [comment]
Thanks!
